<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{c90d7607-1feb-46bb-9bc2-7b1fb026a69c}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'TcCallAfterOutputUpdate'}
PROGRAM MAIN
VAR
	LocalEtherCATDevState	AT%I*:UINT ;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_EtherCATSimMasterDiag();

PRG_EncoderSim();

PRG_AnalogSim();

PRG_SystemFunctions();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>